export enum Action {
    // GENERAL
    SAVE_SETUP_OPTIONS = "@@SAVE_SETUP_OPTIONS",
    PROGRESS_NEXT_STAGE = "@@PROGRESS_NEXT_STAGE",
    LOAD_FROM_DATABASE = "@@LOAD_FROM_DATABASE",
    GET_NEXT_ID = "@@GET_NEXT_ID",

    // ID
    LOAD_NEXT_ID = "@@LOAD_NEXT_ID",
    SAVE_DOCUMENT_TYPE = "@@SAVE_DOCUMENT_TYPE",

    // IMAGE - SEGMENTATION
    LOAD_IMAGE_STATE = "@@LOAD_IMAGE_STATE",
    SAVE_SEG_CHECK = "@@SAVE_SEG_CHECK",
    SET_IMAGE_PROPS = "@@SET_IMAGE_PROPS",
    ADD_ID_BOX = "@@ADD_ID_BOX",
    DELETE_ID_BOX = "@@DELETE_ID_BOX",

    // IMAGE - LANDMARK
    SET_CURRENT_SYMBOL = "@@SET_CURRENT_SYMBOL",
    ADD_LANDMARK_DATA = "@@ADD_LANDMARK_DATA",
    DELETE_LANDMARK_DATA = "@@DELETE_LANDMARK_DATA",
    UPDATE_LANDMARK_FLAGS = "@@UPDATE_LANDMARK_FLAGS",

    // IMAGE - OCR
    ADD_OCR_DATA = "@@ADD_OCR_DATA",
    SET_CURRENT_VALUE = "@@SET_CURRENT_VALUE",
    UPDATE_OCR_DATA = "@@UPDATE_OCR_DATA"
}