export enum Action {
    // GENERAL
    SAVE_SETUP_OPTIONS = "@@SAVE_SETUP_OPTIONS",
    PROGRESS_NEXT_STAGE = "@@PROGRESS_NEXT_STAGE",
    LOAD_FROM_DATABASE = "@@LOAD_FROM_DATABASE",
    GET_NEXT_IMAGE = "@@GET_NEXT_IMAGE",

    // IMAGE
    LOAD_IMAGE_STATE = "@@LOAD_IMAGE_STATE"
}